spring.application.name=AUTH-SERVICE

#configure rabbitmq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=secret

notification.email.from=himanshu43.work@gmail.com

spring.cloud.function.definition=UserCreatedEvent;UserVerifiedEvent;WelcomeEmailEvent;OtpEvent;ResetPasswordEvent

#configure spring cloud stream
spring.cloud.stream.bindings.UserCreatedEvent-out-0.destination=user.created
spring.cloud.stream.bindings.UserCreatedEvent-out-0.contentType=application/json
spring.cloud.stream.bindings.UserCreatedEvent-out-0.group=${spring.application.name}


spring.cloud.stream.bindings.UserVerifiedEvent-out-0.destination=user.verified
spring.cloud.stream.bindings.UserVerifiedEvent-out-0.contentType=application/json
spring.cloud.stream.bindings.UserVerifiedEvent-out-0.group=${spring.application.name}


spring.cloud.stream.bindings.WelcomeEmailEvent-out-0.destination=user.created.welcomeEmail
spring.cloud.stream.bindings.WelcomeEmailEvent-out-0.contentType=application/json
spring.cloud.stream.bindings.WelcomeEmailEvent-out-0.group=${spring.application.name}

spring.cloud.stream.bindings.OtpEvent-out-0.destination=otp.send
spring.cloud.stream.bindings.OtpEvent-out-0.contentType=application/json
spring.cloud.stream.bindings.OtpEvent-out-0.group=${spring.application.name}

spring.cloud.stream.bindings.ResetPasswordEvent-out-0.destination=password.reset.email
spring.cloud.stream.bindings.ResetPasswordEvent-out-0.contentType=application/json
spring.cloud.stream.bindings.ResetPasswordEvent-out-0.group=${spring.application.name}