server:
  port: 13002

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

auth:
  otp:
    length: 6
    ttl-seconds: 300
    max-attempts: 5
    expose-in-response: true
  jwt:
    secret: ksnkka1nlmldmwo12421fonwdvsyjwndbbskb3212kdbi35687bwknlndlwnkjnifckfndfdf345wedgrhykrtwfeuk9
    expiration: 3600000 # 1 hour
    refresh-expiration: 2592000000 # 30 days