spring.application.name=NOTIFICATION-SERVICE

server.port = 13006

# Database configuration
spring.datasource.url=jdbc:h2:mem:notification_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# H2 CONSOLE
# ===============================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# application.properties
spring.jpa.defer-datasource-initialization=true


spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a2fcf7001@smtp-brevo.com
spring.mail.password=fFOGAx5MRHTgCv38
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=himanshubhatt1254@gmail.com


#===================================== RabbitMQ Configuration =====================================

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=secret

spring.cloud.function.definition=WelcomeEmailEvent;OtpEvent;ResetPasswordEvent

#configure spring cloud stream
spring.cloud.stream.bindings.WelcomeEmailEvent-in-0.destination=user.created.welcomeEmail
spring.cloud.stream.bindings.WelcomeEmailEvent-in-0.contentType=application/json
spring.cloud.stream.bindings.WelcomeEmailEvent-in-0.group=${spring.application.name}

spring.cloud.stream.bindings.ResetPasswordEvent-in-0.destination=password.reset.email
spring.cloud.stream.bindings.ResetPasswordEvent-in-0.contentType=application/json
spring.cloud.stream.bindings.ResetPasswordEvent-in-0.group=${spring.application.name}

spring.cloud.stream.bindings.OtpEvent-in-0.destination=otp.send
spring.cloud.stream.bindings.OtpEvent-in-0.contentType=application/json
spring.cloud.stream.bindings.OtpEvent-in-0.group=${spring.application.name}