spring.application.name=EXPENSE-SERVICE

server.port = 13004

# ===============================
# H2 DATABASE CONFIG
# ===============================

spring.datasource.url=jdbc:h2:mem:expense_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===============================
# H2 CONSOLE
# ===============================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# application.properties
spring.jpa.defer-datasource-initialization=true


#configure spring cloud stream
spring.cloud.stream.bindings.GetAllExpense-in-0.destination=user.expense.getAllExpense
spring.cloud.stream.bindings.GetAllExpense-in-0.contentType=application/json
spring.cloud.stream.bindings.GetAllExpense-in-0.group=${spring.application.name}

#spring.cloud.stream.bindings.ResetPasswordEvent-in-0.destination=password.reset.email
#spring.cloud.stream.bindings.ResetPasswordEvent-in-0.contentType=application/json
#spring.cloud.stream.bindings.ResetPasswordEvent-in-0.group=${spring.application.name}
#
#spring.cloud.stream.bindings.OtpEvent-in-0.destination=otp.send
#spring.cloud.stream.bindings.OtpEvent-in-0.contentType=application/json
#spring.cloud.stream.bindings.OtpEvent-in-0.group=${spring.application.name}
