#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:13001/eureka/
#  instance:
#    hostname: localhost
#    prefer-ip-address: false
#    instance-id: ${spring.application.name}:${server.port}
