spring.application.name=PROFILE-SERVICE

server.port=13003

# ===============================
# H2 DATABASE CONFIG
# ===============================

spring.datasource.url=jdbc:h2:mem:profiledb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# H2 CONSOLE
# ===============================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# application.properties
spring.jpa.defer-datasource-initialization=true

# server.servlet.context-path=/profile


#configure rabbitmq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=secret

spring.cloud.function.definition=UserCreatedEvent;UserVerifiedEvent

#configure spring cloud stream
spring.cloud.stream.bindings.UserCreatedEvent-in-0.destination=user.created
spring.cloud.stream.bindings.UserCreatedEvent-in-0.contentType=application/json
spring.cloud.stream.bindings.UserCreatedEvent-in-0.group=${spring.application.name}

spring.cloud.stream.bindings.UserVerifiedEvent-in-0.destination=user.verified
spring.cloud.stream.bindings.UserVerifiedEvent-in-0.contentType=application/json
spring.cloud.stream.bindings.UserVerifiedEvent-in-0.group=${spring.application.name}
